language: python

python:
  - "3.4"

build:
  pre_ci_boot:
    image_name: gcr.io/clustree-cloud/shippable-ubuntu-1510
    image_tag: latest
    pull: true
  ci:
    - virtualenv -p /usr/bin/python$SHIPPABLE_PYTHON_VERSION $HOME/clustree_ve
    - source $HOME/clustree_ve/bin/activate
    - pip install pytest
    - py.test --verbose
